/*
 * File generated by Graphback CRUD resolver plugin.
 * Content will be overwritten by Graphback generator.
 * To change implementation please disable generator options and supply your own implementation
 * outside generated file.
 */

export default {
  Post: {
    author: (parent, args, context) => {
      return context.User.findBy({ id: parent.authorId }).then(
        (results) => results[0]
      )
    },
  },

  User: {
    posts: (parent, args, context) => {
      return context.Post.batchLoadData("authorId", parent.id, context)
    },
  },

  Query: {
    findPosts: (parent, args, context) => {
      const { fields, ...page } = args
      return context.Post.findBy(fields, page)
    },
    findAllPosts: (parent, args, context) => {
      return context.Post.findAll(args)
    },
    findUsers: (parent, args, context) => {
      const { fields, ...page } = args
      return context.User.findBy(fields, page)
    },
    findAllUsers: (parent, args, context) => {
      return context.User.findAll(args)
    },
  },

  Mutation: {
    createPost: (parent, args, context) => {
      return context.Post.create(args.input, context)
    },
    updatePost: (parent, args, context) => {
      return context.Post.update(args.input, context)
    },
    deletePost: (parent, args, context) => {
      return context.Post.delete(args.input, context)
    },
    createUser: (parent, args, context) => {
      return context.User.create(args.input, context)
    },
    updateUser: (parent, args, context) => {
      return context.User.update(args.input, context)
    },
    deleteUser: (parent, args, context) => {
      return context.User.delete(args.input, context)
    },
  },

  Subscription: {
    newPost: {
      subscribe: (parent, args, context) => {
        return context.Post.subscribeToCreate(args, context)
      },
    },
    updatedPost: {
      subscribe: (parent, args, context) => {
        return context.Post.subscribeToUpdate(args, context)
      },
    },
    deletedPost: {
      subscribe: (parent, args, context) => {
        return context.Post.subscribeToDelete(args, context)
      },
    },
    newUser: {
      subscribe: (parent, args, context) => {
        return context.User.subscribeToCreate(args, context)
      },
    },
    updatedUser: {
      subscribe: (parent, args, context) => {
        return context.User.subscribeToUpdate(args, context)
      },
    },
    deletedUser: {
      subscribe: (parent, args, context) => {
        return context.User.subscribeToDelete(args, context)
      },
    },
  },
}
